services:
  authelia:
    build:
      context: ./
      dockerfile: authelia.Dockerfile
    container_name: authelia
    environment:
      - TZ=UTC
    networks:
      - frontend
    volumes:
      - ./config:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 1m