services:

  openwebui:
    image: openwebui/open-webui
    container_name: openwebui
    networks:
      - frontend
      - backend
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama-cpu
      - ollama-gpu

  ollama-cpu:
    image: ollama/ollama
    container_name: ollama-cpu
    networks:
      - backend
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  ollama-gpu:
    image: ollama/ollama
    container_name: ollama-gpu
    networks:
      - backend
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  caddy:
    image: caddy:latest
    container_name: caddy
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/conf:/etc/caddy
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - openwebui 
    restart: unless-stopped

volumes:
  open-webui:
    name: open-webui
  caddy-data:
    name: caddy-data
  caddy-config:
    name: caddy-config
  ollama:
    name: ollama

networks:
  frontend:
  backend: