services:
  grafana:
    build:
      context: services/grafana/
      dockerfile: grafana.Dockerfile
    container_name: grafana
    networks:
      - backend
      - frontend
    ports:
      - 2999:3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-data:
    name: grafana-data

networks:
  backend:
    external: true
  frontend:
    external: true