services:
  caddy:
    build:
      context: ./
      dockerfile: caddy.Dockerfile
    container_name: caddy
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      open-webui:
        condition: service_healthy
    restart: unless-stopped

volumes:
  caddy-data:
    name: caddy-data
  caddy-config:
    name: caddy-config